name: Code Quality
on: [Push]
jobs:
  lint-and-format:
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: action/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Check Prettier
        run: pnpm run format

      - name: ESLint
        run: pnpm run lint
